Repository openfun/edx-platform, pull requests merged in 2020-01, with the labels that each got.

#58 🔖(fix) bump version to dogwood.3-fun-5.3.1
  CHANGELOG.md
Labels: FUN

#59 🗃(certificates) change url path to FUN's PDF certificates
  lms/templates/dashboard/_dashboard_certificate_information.html
Labels: FUN, bug

#60 🔖(fix) bump version to dogwood.3-fun-5.3.2
  CHANGELOG.md
  CHANGELOG.rst
Labels: bug, critical
